export const SITE_CONFIG = {
  name: 'Chiloba Mwabu',
  tagline: 'Professional Mathematics Educator • Career Consultant • Master of Ceremonies • Gospel Music Director • Lukwanga FM Radio Host',
  description: 'Empowering students, inspiring audiences, and transforming careers through education, consulting, and ministry.',
  url: 'https://chilobamwabu.com',
  email: 'hello@chilobamwabu.com',
  phone: '+260 977 230 272',
  whatsapp: '+260 977 230 272',
  address: 'Lusaka, Zambia',
  social: {
    twitter: 'https://twitter.com/chilobamwabu',
    linkedin: 'https://linkedin.com/in/chilobamwabu',
    youtube: 'https://youtube.com/@chilobamwabu',
    facebook: 'https://facebook.com/chilobamwabu',
    instagram: 'https://instagram.com/chilobamwabu',
  },
} as const;

export const NAV_ITEMS = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Services', href: '/services' },
  { label: 'Resources', href: '/resources' },
  { label: 'Gallery', href: '/gallery' },
  { label: 'Testimonials', href: '/testimonials' },
  { label: 'Career Hub', href: '/career-hub' },
  { label: 'Bookings', href: '/bookings' },
  { label: 'Contact', href: '/contact' },
] as const;

export const STATS = [
  { label: 'Students Taught', value: 5000, suffix: '+' },
  { label: 'Resources', value: 200, suffix: '+' },
  { label: 'Events Hosted', value: 150, suffix: '+' },
  { label: 'Career Sessions', value: 80, suffix: '+' },
] as const;

export const RESOURCE_CATEGORIES = [
  'Grade 10',
  'Grade 11',
  'Grade 12',
  'Tertiary',
  'Career Resources',
  'Study Guides',
  'Revision Packs',
  'Formula Sheets',
  'Past Papers',
  'Marking Schemes',
] as const;

export const RESOURCE_DIFFICULTIES = ['Beginner', 'Intermediate', 'Advanced', 'Expert'] as const;

export const RESOURCE_TYPES = ['PDF', 'DOCX', 'ZIP', 'VIDEO', 'IMAGE', 'AUDIO'] as const;

export const BOOKING_SERVICES = [
  'Mathematics Tuition',
  'Career Consultation',
  'MC Services',
  'Music Ministry',
  'Radio Interview',
  'School Seminar',
  'Corporate Event',
] as const;

export const DAYS_OF_WEEK = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] as const;

export const AVAILABILITY = {
  Sunday: 'Available',
  Monday: 'Available',
  Tuesday: 'Available',
  Wednesday: 'Available',
  Thursday: 'Available',
  Friday: 'Available',
  Saturday: 'Unavailable',
} as const;

export const CAREER_QUESTIONS = [
  {
    id: 'q1',
    question: 'What is your favorite school subject?',
    options: [
      { label: 'Mathematics', value: 5 },
      { label: 'Science', value: 4 },
      { label: 'English', value: 3 },
      { label: 'History', value: 2 },
      { label: 'Arts', value: 1 },
      { label: 'Technology', value: 5 },
    ],
  },
  {
    id: 'q2',
    question: 'What are your career interests?',
    options: [
      { label: 'Engineering', value: 5 },
      { label: 'Medicine', value: 4 },
      { label: 'Finance', value: 4 },
      { label: 'Education', value: 5 },
      { label: 'Technology', value: 5 },
      { label: 'Arts & Media', value: 3 },
    ],
  },
  {
    id: 'q3',
    question: 'What are your key strengths?',
    options: [
      { label: 'Problem Solving', value: 5 },
      { label: 'Communication', value: 4 },
      { label: 'Leadership', value: 4 },
      { label: 'Creativity', value: 3 },
      { label: 'Analytical Thinking', value: 5 },
      { label: 'Teamwork', value: 3 },
    ],
  },
  {
    id: 'q4',
    question: 'What is your primary goal?',
    options: [
      { label: 'University Admission', value: 5 },
      { label: 'Career Success', value: 4 },
      { label: 'Financial Independence', value: 3 },
      { label: 'Making a Difference', value: 5 },
      { label: 'Creative Expression', value: 2 },
    ],
  },
  {
    id: 'q5',
    question: 'Which work environment suits you best?',
    options: [
      { label: 'Office/Corporate', value: 3 },
      { label: 'Remote/Flexible', value: 4 },
      { label: 'Teaching/Training', value: 5 },
      { label: 'Creative Studio', value: 2 },
      { label: 'Field Work', value: 3 },
    ],
  },
] as const;

export const CAREER_RECOMMENDATIONS = [
  {
    career: 'Mathematics Educator',
    description: 'Share your passion for mathematics with students at various levels.',
    universityCourses: ['BSc Mathematics Education', 'BEd Mathematics', 'Applied Mathematics'],
    recommendedResources: ['Grade 12 Past Papers', 'Tertiary Mathematics Formula Sheets', 'Teaching Methodology Guide'],
    professionalAdvice: 'Consider pursuing a BEd or BSc in Mathematics Education. Gain teaching experience through volunteer tutoring and internships.',
    score: 95,
  },
  {
    career: 'Data Analyst',
    description: 'Transform raw data into actionable insights for businesses and organizations.',
    universityCourses: ['BSc Data Science', 'BSc Statistics', 'BSc Mathematics with Computing'],
    recommendedResources: ['Career Resources: Data Analysis', 'Advanced Mathematics Revision Pack', 'Statistical Methods Guide'],
    professionalAdvice: 'Learn Python or R programming alongside your mathematics studies. Build a portfolio with real-world data projects.',
    score: 88,
  },
  {
    career: 'Financial Analyst',
    description: 'Guide investment decisions and financial planning for individuals and companies.',
    universityCourses: ['BSc Finance', 'BSc Economics', 'BSc Actuarial Science'],
    recommendedResources: ['Career Resources: Finance', 'Advanced Calculus Revision Pack', 'Financial Mathematics Formula Sheet'],
    professionalAdvice: 'Consider actuarial science for high-demand, well-compensated careers. Supplement with accounting and economics courses.',
    score: 82,
  },
  {
    career: 'Software Engineer',
    description: 'Build innovative software solutions using mathematical principles and algorithms.',
    universityCourses: ['BSc Computer Science', 'BSc Software Engineering', 'BSc Mathematics & Computer Science'],
    recommendedResources: ['Career Resources: Programming', 'Discrete Mathematics Guide', 'Algorithm Design Handbook'],
    professionalAdvice: 'Strong mathematics foundations are key to software engineering. Focus on discrete math, linear algebra, and statistics.',
    score: 85,
  },
  {
    career: 'Operations Research Analyst',
    description: 'Use advanced analytical methods to help organizations make better decisions.',
    universityCourses: ['BSc Operations Research', 'BSc Industrial Mathematics', 'BSc Applied Mathematics'],
    recommendedResources: ['Career Resources: Optimization', 'Linear Algebra Formula Sheet', 'Probability & Statistics Guide'],
    professionalAdvice: 'This field combines mathematics with business strategy. Consider minoring in business or economics alongside your math degree.',
    score: 78,
  },
] as const;

export const SAMPLE_RESOURCES: import('./types').Resource[] = [
  {
    id: 'res-1',
    title: 'Grade 10 Mathematics Core Concepts',
    description: 'Comprehensive coverage of Grade 10 mathematics topics including algebra, geometry, and trigonometry.',
    subject: 'Mathematics',
    topic: 'Algebra & Geometry',
    category: 'Grade 10',
    grade: 'Grade 10',
    type: 'PDF',
    fileSize: '4.2 MB',
    downloads: 1250,
    uploadDate: '2026-01-15',
    premiumStatus: 'free',
    difficulty: 'Beginner',
    estimatedStudyTime: '2 hours',
    thumbnail: '/thumbnails/grade10-math.png',
    url: '#',
    tags: ['algebra', 'geometry', 'grade10'],
    bookmarked: false,
    favorited: false,
  },
  {
    id: 'res-2',
    title: 'Grade 11 Calculus Introduction',
    description: 'Introduction to differential and integral calculus with worked examples and practice problems.',
    subject: 'Mathematics',
    topic: 'Calculus',
    category: 'Grade 11',
    grade: 'Grade 11',
    type: 'PDF',
    fileSize: '5.8 MB',
    downloads: 980,
    uploadDate: '2026-02-01',
    premiumStatus: 'premium',
    difficulty: 'Intermediate',
    estimatedStudyTime: '3 hours',
    thumbnail: '/thumbnails/grade11-calculus.png',
    url: '#',
    tags: ['calculus', 'grade11'],
    bookmarked: false,
    favorited: false,
  },
  {
    id: 'res-3',
    title: 'Grade 12 Past Papers 2024',
    description: 'Complete set of Grade 12 mathematics past papers with marking schemes for exam preparation.',
    subject: 'Mathematics',
    topic: 'Exam Preparation',
    category: 'Past Papers',
    grade: 'Grade 12',
    type: 'ZIP',
    fileSize: '12.5 MB',
    downloads: 2340,
    uploadDate: '2026-03-10',
    premiumStatus: 'premium',
    difficulty: 'Advanced',
    estimatedStudyTime: '10 hours',
    thumbnail: '/thumbnails/grade12-pastpapers.png',
    url: '#',
    tags: ['pastpapers', 'grade12', 'exam'],
    bookmarked: false,
    favorited: false,
  },
  {
    id: 'res-4',
    title: 'Tertiary Mathematics Formula Sheet',
    description: 'Essential formulas for tertiary mathematics including calculus, linear algebra, and statistics.',
    subject: 'Mathematics',
    topic: 'Formulas',
    category: 'Formula Sheets',
    grade: 'Tertiary',
    type: 'PDF',
    fileSize: '1.8 MB',
    downloads: 3100,
    uploadDate: '2026-01-20',
    premiumStatus: 'free',
    difficulty: 'Intermediate',
    estimatedStudyTime: '1 hour',
    thumbnail: '/thumbnails/formula-sheet.png',
    url: '#',
    tags: ['formulas', 'tertiary'],
    bookmarked: false,
    favorited: false,
  },
  {
    id: 'res-5',
    title: 'Career Assessment Guide',
    description: 'Comprehensive guide to career planning with mathematical career pathways and salary expectations.',
    subject: 'Career Resources',
    topic: 'Career Planning',
    category: 'Career Resources',
    grade: 'All Levels',
    type: 'PDF',
    fileSize: '3.1 MB',
    downloads: 890,
    uploadDate: '2026-02-15',
    premiumStatus: 'free',
    difficulty: 'Beginner',
    estimatedStudyTime: '1.5 hours',
    thumbnail: '/thumbnails/career-guide.png',
    url: '#',
    tags: ['career', 'planning', 'guide'],
    bookmarked: false,
    favorited: false,
  },
  {
    id: 'res-6',
    title: 'Grade 12 Revision Pack',
    description: 'Intensive revision pack covering all Grade 12 mathematics topics with practice questions and answers.',
    subject: 'Mathematics',
    topic: 'Revision',
    category: 'Revision Packs',
    grade: 'Grade 12',
    type: 'DOCX',
    fileSize: '6.4 MB',
    downloads: 1560,
    uploadDate: '2026-03-01',
    premiumStatus: 'premium',
    difficulty: 'Advanced',
    estimatedStudyTime: '8 hours',
    thumbnail: '/thumbnails/revision-pack.png',
    url: '#',
    tags: ['revision', 'grade12', 'practice'],
    bookmarked: false,
    favorited: false,
  },
  {
    id: 'res-7',
    title: 'Grade 11 Statistics & Probability',
    description: 'Complete guide to statistics and probability for Grade 11 students with real-world applications.',
    subject: 'Mathematics',
    topic: 'Statistics',
    category: 'Grade 11',
    grade: 'Grade 11',
    type: 'PDF',
    fileSize: '3.7 MB',
    downloads: 1100,
    uploadDate: '2026-01-25',
    premiumStatus: 'free',
    difficulty: 'Intermediate',
    estimatedStudyTime: '2.5 hours',
    thumbnail: '/thumbnails/statistics-prob.png',
    url: '#',
    tags: ['statistics', 'probability', 'grade11'],
    bookmarked: false,
    favorited: false,
  },
  {
    id: 'res-8',
    title: 'Marking Scheme Analysis 2024',
    description: 'Detailed analysis of Grade 10-12 marking schemes with common mistakes and tips.',
    subject: 'Mathematics',
    topic: 'Exam Preparation',
    category: 'Marking Schemes',
    grade: 'Grade 10-12',
    type: 'PDF',
    fileSize: '2.9 MB',
    downloads: 720,
    uploadDate: '2026-03-05',
    premiumStatus: 'premium',
    difficulty: 'Advanced',
    estimatedStudyTime: '2 hours',
    thumbnail: '/thumbnails/marking-scheme.png',
    url: '#',
    tags: ['marking', 'schemes', 'analysis'],
    bookmarked: false,
    favorited: false,
  },
];

export const SAMPLE_TESTIMONIALS = [
  {
    id: 'test-1',
    name: 'Sarah Mwale',
    role: 'Student',
    company: 'University of Zambia',
    rating: 5,
    text: 'Mr. Chiloba transformed my understanding of mathematics. His teaching methods made complex concepts simple and enjoyable. I went from struggling with math to excelling in my exams.',
    avatar: '/avatars/sarah.jpg',
    date: '2026-05-15',
    approved: true,
    featured: true,
    type: 'student',
  },
  {
    id: 'test-2',
    name: 'John Banda',
    role: 'Parent',
    company: 'Lusaka',
    rating: 5,
    text: 'My son has improved tremendously in mathematics since starting tuition with Mr. Chiloba. He is patient, knowledgeable, and truly cares about his students success.',
    avatar: '/avatars/john.jpg',
    date: '2026-04-20',
    approved: true,
    featured: true,
    type: 'parent',
  },
  {
    id: 'test-3',
    name: 'Greenfield High School',
    role: 'School',
    company: 'Lusaka',
    rating: 5,
    text: 'We invited Mr. Chiloba for our annual mathematics seminar. His presentation was engaging, informative, and inspired our students to pursue mathematics further.',
    avatar: '/avatars/school.jpg',
    date: '2026-03-10',
    approved: true,
    featured: false,
    type: 'school',
  },
  {
    id: 'test-4',
    name: 'Grace Phiri',
    role: 'Student',
    company: 'Copperbelt University',
    rating: 5,
    text: 'The career consultation with Mr. Chiloba was a game changer. He helped me identify my strengths and choose the right university course. I am now thriving in my studies.',
    avatar: '/avatars/grace.jpg',
    date: '2026-06-01',
    approved: true,
    featured: true,
    type: 'student',
  },
  {
    id: 'test-5',
    name: 'Kingdom Ministries',
    role: 'Church',
    company: 'Lusaka',
    rating: 5,
    text: 'Mr. Chiloba directed our gospel music ministry for the annual concert. His leadership and musical talent brought the congregation to their feet.',
    avatar: '/avatars/church.jpg',
    date: '2026-02-14',
    approved: true,
    featured: false,
    type: 'church',
  },
];

export const SAMPLE_SERVICES = [
  {
    id: 'svc-1',
    title: 'Mathematics Education',
    description: 'Comprehensive mathematics tuition for Grade 10-12 and tertiary students. Covering algebra, calculus, statistics, and exam preparation.',
    icon: 'Calculator',
    category: 'Education',
    price: 'From $20/hour',
    features: ['One-on-one tutoring', 'Group sessions', 'Exam preparation', 'Homework help', 'Progress tracking'],
    popular: true,
  },
  {
    id: 'svc-2',
    title: 'Career Consultation',
    description: 'Professional career guidance and assessment. Help you discover your strengths and find the right career path.',
    icon: 'Briefcase',
    category: 'Consulting',
    price: 'From $50/session',
    features: ['Career assessment', 'University guidance', 'Resume building', 'Interview prep', 'Follow-up support'],
    popular: false,
  },
  {
    id: 'svc-3',
    title: 'Master of Ceremonies',
    description: 'Professional MC services for weddings, corporate events, conferences, and social gatherings.',
    icon: 'Mic',
    category: 'Entertainment',
    price: 'From $150/event',
    features: ['Event hosting', 'Audience engagement', 'Program coordination', 'Sound management', 'Custom scripts'],
    popular: false,
  },
  {
    id: 'svc-4',
    title: 'Music Ministry',
    description: 'Gospel music direction and ministry services for churches and religious events.',
    icon: 'Music',
    category: 'Ministry',
    price: 'From $100/event',
    features: ['Music direction', 'Choir training', 'Song arrangement', 'Sound production', 'Worship leading'],
    popular: false,
  },
  {
    id: 'svc-5',
    title: 'Radio Hosting',
    description: 'Professional radio hosting and production services for Lukwanga FM and partner stations.',
    icon: 'Radio',
    category: 'Media',
    price: 'From $200/episode',
    features: ['Show hosting', 'Content creation', 'Interview skills', 'Audio production', 'Audience engagement'],
    popular: false,
  },
  {
    id: 'svc-6',
    title: 'Educational Workshops',
    description: 'Interactive workshops on mathematics, study skills, and career development for schools and organizations.',
    icon: 'GraduationCap',
    category: 'Education',
    price: 'From $300/workshop',
    features: ['Custom curriculum', 'Interactive sessions', 'Materials provided', 'Certification', 'Follow-up resources'],
    popular: false,
  },
  {
    id: 'svc-7',
    title: 'School Seminars',
    description: 'Motivational and educational seminars for schools on mathematics, career guidance, and personal development.',
    icon: 'School',
    category: 'Education',
    price: 'From $250/seminar',
    features: ['Motivational talks', 'Study techniques', 'Career guidance', 'Exam tips', 'Q&A sessions'],
    popular: false,
  },
  {
    id: 'svc-8',
    title: 'Exam Preparation',
    description: 'Intensive exam preparation programs for Grade 10-12 and tertiary mathematics examinations.',
    icon: 'FileText',
    category: 'Education',
    price: 'From $30/session',
    features: ['Past paper practice', 'Marking scheme analysis', 'Time management', 'Exam techniques', 'Mock exams'],
    popular: false,
  },
  {
    id: 'svc-9',
    title: 'University Guidance',
    description: 'Guidance on university selection, application processes, and scholarship opportunities.',
    icon: 'University',
    category: 'Consulting',
    price: 'From $40/session',
    features: ['University selection', 'Application support', 'Scholarship guidance', 'Personal statements', 'Interview prep'],
    popular: false,
  },
  {
    id: 'svc-10',
    title: 'Church Programs',
    description: 'Comprehensive church program planning and execution including music ministry and event coordination.',
    icon: 'Church',
    category: 'Ministry',
    price: 'From $200/program',
    features: ['Program planning', 'Music direction', 'Event coordination', 'Volunteer management', 'Worship design'],
    popular: false,
  },
  {
    id: 'svc-11',
    title: 'Corporate Events',
    description: 'Professional event management and MC services for corporate functions and business conferences.',
    icon: 'Building',
    category: 'Entertainment',
    price: 'From $300/event',
    features: ['Event planning', 'Professional hosting', 'Audience engagement', 'Brand alignment', 'Post-event report'],
    popular: false,
  },
  {
    id: 'svc-12',
    title: 'Study Skills Workshop',
    description: 'Workshops on effective study techniques, time management, and learning strategies for students.',
    icon: 'BookOpen',
    category: 'Education',
    price: 'From $25/student',
    features: ['Study techniques', 'Time management', 'Note-taking', 'Memory methods', 'Exam strategies'],
    popular: false,
  },
];

export const SAMPLE_GALLERY = [
  { id: 'gal-1', title: 'Teaching Mathematics', category: 'teaching', url: '/gallery/teaching-1.jpg', thumbnail: '/gallery/teaching-1-thumb.jpg', description: 'In-class mathematics teaching session', date: '2026-06-15' },
  { id: 'gal-2', title: 'School Seminar', category: 'events', url: '/gallery/events-1.jpg', thumbnail: '/gallery/events-1-thumb.jpg', description: 'Annual school mathematics seminar', date: '2026-05-20' },
  { id: 'gal-3', title: 'Church Ministry', category: 'church', url: '/gallery/church-1.jpg', thumbnail: '/gallery/church-1-thumb.jpg', description: 'Gospel music ministry session', date: '2026-04-10' },
  { id: 'gal-4', title: 'Music Production', category: 'music', url: '/gallery/music-1.jpg', thumbnail: '/gallery/music-1-thumb.jpg', description: 'Recording session at the studio', date: '2026-03-22' },
  { id: 'gal-5', title: 'Radio Broadcast', category: 'radio', url: '/gallery/radio-1.jpg', thumbnail: '/gallery/radio-1-thumb.jpg', description: 'Live broadcast at Lukwanga FM', date: '2026-06-01' },
  { id: 'gal-6', title: 'Students Success', category: 'students', url: '/gallery/students-1.jpg', thumbnail: '/gallery/students-1-thumb.jpg', description: 'Students celebrating exam results', date: '2026-02-15' },
  { id: 'gal-7', title: 'Award Ceremony', category: 'awards', url: '/gallery/awards-1.jpg', thumbnail: '/gallery/awards-1-thumb.jpg', description: 'Receiving the Educator of the Year award', date: '2026-01-30' },
  { id: 'gal-8', title: 'Corporate Event', category: 'events', url: '/gallery/events-2.jpg', thumbnail: '/gallery/events-2-thumb.jpg', description: 'Hosting a corporate conference', date: '2026-05-05' },
];